import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Skeleton } from "@/components/ui/skeleton";
import { Textarea } from "@/components/ui/textarea";
import { BRAND_QUIZ, BRAND_QUIZ_TOTAL } from "@shared/brandQuiz";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, ArrowRight, Check, Download, Heart, Loader2, Palette, Printer, RefreshCw, Sparkles, Type } from "lucide-react";
import { toast } from "sonner";
import { useState } from "react";
import { useLocation, useParams } from "wouter";

type PaletteColor = { name: string; hex: string; use: string };
type DirectionData = { title:string; essence:string; visualStyle:string; palette:PaletteColor[]; typography:{display:string;body:string;scale:{h1:string;h2:string;body:string;label:string}}; logoConcept:string; imagery:string; voice:string; site:{headline:string;description:string;sections:Array<{title:string;purpose:string}>} };
type DirectionRow = { id:number; round:number; optionKey:string; title:string; status:string; logoImageUrl:string|null; content:Record<string,unknown>; isFavorite:boolean; parentDirectionId:number|null; explorationDepth:number };
const parseDirection=(d:DirectionRow)=>d.content as unknown as DirectionData;
function LogoFallback({title,className=""}:{title:string;className?:string}){const initials=title.split(" ").slice(0,2).map(w=>w[0]).join("").toUpperCase();return <div className={`grid place-items-center bg-sand font-display text-4xl text-ink ${className}`}>{initials}</div>}

export default function BrandWorkspace(){
 const params=useParams<{brandId:string}>(); const brandId=Number(params.brandId); const [,setLocation]=useLocation(); const utils=trpc.useUtils();
 const [showFavorites,setShowFavorites]=useState(false); const [isRefinementOpen,setIsRefinementOpen]=useState(false); const [refinementNote,setRefinementNote]=useState("");
 const workspace=trpc.brand.getWorkspace.useQuery({brandId},{enabled:Number.isFinite(brandId)&&brandId>0});
 const refresh=()=>utils.brand.getWorkspace.invalidate({brandId});
 const answer=trpc.brand.answer.useMutation({onSuccess:refresh,onError:e=>toast.error(e.message)});
 const generate=trpc.brand.generate.useMutation({onSuccess:refresh,onError:e=>toast.error(e.message)});
 const regenerate=trpc.brand.regenerate.useMutation({onSuccess:refresh,onError:e=>toast.error(e.message)});
 const favorite=trpc.brand.favorite.useMutation({onSuccess:refresh,onError:e=>toast.error(e.message)});
 const explore=trpc.brand.explore.useMutation({onSuccess:()=>{setShowFavorites(false);refresh();toast.success("Criamos cinco novas variações a partir desta direção.")},onError:e=>toast.error(e.message)});
 const choose=trpc.brand.choose.useMutation({onSuccess:()=>{refresh();toast.success("Identidade escolhida. O brand book está pronto.")},onError:e=>toast.error(e.message)});
 const approveSite=trpc.brand.approveSite.useMutation({onSuccess:refresh,onError:e=>toast.error(e.message)});
 if(workspace.isLoading)return <DashboardLayout><div className="mx-auto max-w-6xl space-y-5 px-5 py-10"><Skeleton className="h-10 w-56"/><Skeleton className="h-[560px] rounded-[2rem]"/></div></DashboardLayout>;
 if(workspace.isError||!workspace.data)return <DashboardLayout><div className="mx-auto max-w-xl px-5 py-20 text-center"><p className="font-display text-4xl">Não foi possível abrir esta marca.</p></div></DashboardLayout>;
 const {brand,session,directions,favorites,selectedDirection}=workspace.data; const answers=(session?.answers??{}) as Record<string,string>; const nextQuestionIndex=BRAND_QUIZ.findIndex(q=>!answers[q.id]); const isComplete=nextQuestionIndex===-1; const isBusy=generate.isPending||regenerate.isPending||explore.isPending||session?.status==="generating";
 const active=directions.filter(d=>d.round===session?.currentRound&&d.status==="proposed").sort((a,b)=>a.optionKey.localeCompare(b.optionKey)) as DirectionRow[];
 const toggleFavorite=(d:DirectionRow)=>session&&favorite.mutate({sessionId:session.id,directionId:d.id,favorite:!d.isFavorite});
 const exploreDirection=(d:DirectionRow)=>session&&explore.mutate({sessionId:session.id,directionId:d.id});
 const chooseDirection=(d:DirectionRow)=>session&&choose.mutate({sessionId:session.id,directionId:d.id});
 function requestRefinement(){if(!session)return;const note=refinementNote.trim();if(note.length<8){toast.error("Conte um pouco mais sobre o que você quer mudar.");return}regenerate.mutate({sessionId:session.id,refinementNote:note},{onSuccess:()=>{setIsRefinementOpen(false);setRefinementNote("")}})}
 return <DashboardLayout><div className="mx-auto max-w-6xl px-3 py-5 sm:px-5 sm:py-8">
  <button onClick={()=>setLocation("/")} className="inline-flex items-center gap-2 text-sm font-medium text-muted-foreground"><ArrowLeft className="h-4 w-4"/> Acervo de marcas</button>
  <header className="mt-7 flex flex-col justify-between gap-5 border-b border-stone-200 pb-6 sm:flex-row sm:items-end"><div><p className="eyebrow">Diagnóstico de identidade</p><h1 className="mt-2 font-display text-5xl text-ink">{brand.name}</h1></div><div className="flex items-center gap-2"><Button variant="outline" onClick={()=>setShowFavorites(!showFavorites)} className="rounded-full"><Heart className={`mr-2 h-4 w-4 ${favorites.length?"fill-current":""}`}/> Favoritas <Badge className="ml-2">{favorites.length}</Badge></Button><Badge variant="outline" className="rounded-full">{session?.status==="selected"?"Identidade definida":"Em construção"}</Badge></div></header>
  {showFavorites&&!selectedDirection?<FavoritesGallery directions={favorites as DirectionRow[]} onFavorite={toggleFavorite} onExplore={exploreDirection} onChoose={chooseDirection} busy={favorite.isPending||explore.isPending||choose.isPending}/>:selectedDirection?<><BrandBook direction={selectedDirection as DirectionRow} brandName={brand.name} siteApproved={session?.siteApproved??false} onApproveSite={()=>session&&approveSite.mutate({sessionId:session.id})} onExport={()=>window.print()} onOpenRefinement={()=>setIsRefinementOpen(true)}/>{isRefinementOpen&&<RefinementPanel value={refinementNote} onChange={setRefinementNote} onCancel={()=>setIsRefinementOpen(false)} onSubmit={requestRefinement} loading={regenerate.isPending}/>}</>:!isComplete?<QuizStep questionIndex={nextQuestionIndex} answers={answers} onChoose={o=>{const q=BRAND_QUIZ[nextQuestionIndex];if(q&&session)answer.mutate({sessionId:session.id,questionId:q.id,option:o})}} loading={answer.isPending}/>:isBusy?<GeneratingState brandName={brand.name}/>:active.length===5?<ExplorationGallery directions={active} favoritesCount={favorites.length} onFavorite={toggleFavorite} onExplore={exploreDirection} onFinish={()=>setShowFavorites(true)} busy={favorite.isPending||explore.isPending}/>:<ReadyToGenerate brandName={brand.name} onGenerate={()=>session&&generate.mutate({sessionId:session.id})} loading={generate.isPending}/>} 
 </div></DashboardLayout>
}

function QuizStep({questionIndex,answers,onChoose,loading}:{questionIndex:number;answers:Record<string,string>;onChoose:(o:"A"|"B"|"C"|"D"|"E")=>void;loading:boolean}){const q=BRAND_QUIZ[questionIndex];return <section className="mx-auto mt-10 max-w-4xl"><div className="mb-8 flex justify-between"><div><p className="eyebrow">{q.category}</p><p className="mt-2 text-sm text-muted-foreground">Pergunta {questionIndex+1} de {BRAND_QUIZ_TOTAL}</p></div><div className="w-40"><Progress value={(Object.keys(answers).length/BRAND_QUIZ_TOTAL)*100}/></div></div><Card><CardContent className="p-8"><h2 className="font-display text-4xl">{q.prompt}</h2><p className="mt-4 text-sm text-muted-foreground">{q.helper}</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{q.options.map(o=><button key={o.id} disabled={loading} onClick={()=>onChoose(o.id)} className="rounded-2xl border p-5 text-left hover:border-olive hover:bg-sand"><strong>{o.id} · {o.label}</strong><span className="mt-1 block text-xs text-muted-foreground">{o.detail}</span></button>)}</div></CardContent></Card></section>}
function ReadyToGenerate({brandName,onGenerate,loading}:{brandName:string;onGenerate:()=>void;loading:boolean}){return <section className="mx-auto mt-10 max-w-3xl rounded-[2rem] bg-ink px-8 py-14 text-center text-ivory"><Sparkles className="mx-auto text-champagne"/><p className="mt-6 eyebrow text-champagne">Diagnóstico completo</p><h2 className="mt-4 font-display text-5xl">Vamos explorar {brandName}.</h2><p className="mx-auto mt-5 max-w-xl text-sm text-ivory/70">Começaremos com cinco territórios. Favorite quantos quiser e aprofunde qualquer direção para gerar novas variações.</p><Button onClick={onGenerate} disabled={loading} className="mt-8 rounded-full bg-champagne text-ink">{loading?<Loader2 className="animate-spin"/>:<>Gerar 5 direções <ArrowRight className="ml-2 h-4 w-4"/></>}</Button></section>}
function GeneratingState({brandName}:{brandName:string}){return <section className="mx-auto mt-10 max-w-3xl rounded-[2rem] border bg-white px-8 py-16 text-center"><Loader2 className="mx-auto h-10 w-10 animate-spin text-olive"/><h2 className="mt-6 font-display text-5xl">Explorando o universo de {brandName}.</h2><p className="mt-4 text-sm text-muted-foreground">A IA está criando cinco possibilidades visuais.</p></section>}

function ExplorationGallery({directions,favoritesCount,onFavorite,onExplore,onFinish,busy}:{directions:DirectionRow[];favoritesCount:number;onFavorite:(d:DirectionRow)=>void;onExplore:(d:DirectionRow)=>void;onFinish:()=>void;busy:boolean}){return <section className="mt-10"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div className="max-w-2xl"><p className="eyebrow">Exploração criativa</p><h2 className="mt-3 font-display text-5xl">Guarde o que gostar. Explore o que despertar algo.</h2><p className="mt-4 text-sm text-muted-foreground">O coração salva uma direção. “Explorar” cria cinco descendentes dela sem apagar suas favoritas.</p></div>{favoritesCount>0&&<Button onClick={onFinish} className="rounded-full bg-ink text-ivory"><Heart className="mr-2 h-4 w-4 fill-current"/> Ver minhas {favoritesCount} favoritas</Button>}</div><div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{directions.map(d=><DirectionCard key={d.id} direction={d} onFavorite={()=>onFavorite(d)} onExplore={()=>onExplore(d)} busy={busy}/>)}</div></section>}
function DirectionCard({direction,onFavorite,onExplore,busy}:{direction:DirectionRow;onFavorite:()=>void;onExplore:()=>void;busy:boolean}){const data=parseDirection(direction);return <Card className="overflow-hidden"><CardContent className="p-0"><div className="relative grid min-h-56 place-items-center" style={{background:data.palette?.[0]?.hex??"#eee"}}><span className="absolute left-4 top-4 rounded-full bg-white/90 px-3 py-1 text-xs">{direction.optionKey}{direction.explorationDepth>0?` · nível ${direction.explorationDepth}`:""}</span><button aria-label="Favoritar" onClick={onFavorite} disabled={busy} className="absolute right-4 top-4 grid h-10 w-10 place-items-center rounded-full bg-white shadow"><Heart className={`h-5 w-5 ${direction.isFavorite?"fill-red-500 text-red-500":"text-ink"}`}/></button>{direction.logoImageUrl?<img src={direction.logoImageUrl} className="h-32 w-32 rounded-2xl object-cover"/>:<LogoFallback title={data.title} className="h-32 w-32 rounded-2xl"/>}</div><div className="p-6"><p className="eyebrow">{data.visualStyle}</p><h3 className="mt-2 font-display text-3xl">{data.title}</h3><p className="mt-4 text-sm text-muted-foreground">{data.essence}</p><div className="mt-5 flex gap-1.5">{data.palette?.map(c=><span key={c.hex} className="h-5 w-5 rounded-full border" style={{background:c.hex}}/>)}</div><Button onClick={onExplore} disabled={busy} variant="outline" className="mt-6 w-full rounded-full"><Sparkles className="mr-2 h-4 w-4"/> Explorar esta direção</Button></div></CardContent></Card>}
function FavoritesGallery({directions,onFavorite,onExplore,onChoose,busy}:{directions:DirectionRow[];onFavorite:(d:DirectionRow)=>void;onExplore:(d:DirectionRow)=>void;onChoose:(d:DirectionRow)=>void;busy:boolean}){return <section className="mt-10"><p className="eyebrow">Sua curadoria</p><h2 className="mt-3 font-display text-5xl">Suas favoritas, lado a lado.</h2><p className="mt-4 text-sm text-muted-foreground">Você pode continuar explorando ou escolher a identidade vencedora.</p>{directions.length===0?<div className="mt-8 rounded-2xl border border-dashed p-10 text-center text-muted-foreground">Você ainda não favoritou nenhuma direção.</div>:<div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{directions.map(d=><div key={d.id}><DirectionCard direction={d} onFavorite={()=>onFavorite(d)} onExplore={()=>onExplore(d)} busy={busy}/><Button onClick={()=>onChoose(d)} disabled={busy} className="mt-2 w-full rounded-full bg-ink text-ivory"><Check className="mr-2 h-4 w-4"/> Escolher como identidade final</Button></div>)}</div>}</section>}

function BrandBook({direction,brandName,siteApproved,onApproveSite,onExport,onOpenRefinement}:{direction:DirectionRow;brandName:string;siteApproved:boolean;onApproveSite:()=>void;onExport:()=>void;onOpenRefinement:()=>void}){const data=parseDirection(direction);return <section className="mt-10"><div className="mb-5 flex flex-wrap justify-between gap-3 rounded-2xl border bg-white p-5"><div><p className="eyebrow">Identidade aprovada</p><p className="text-sm text-muted-foreground">Sua direção vencedora está pronta para evoluir para o Brand Kit.</p></div><div className="flex gap-2"><Button onClick={onExport} variant="outline" className="rounded-full"><Download className="mr-2 h-4 w-4"/>PDF</Button><Button onClick={onOpenRefinement} className="rounded-full bg-ink text-ivory"><RefreshCw className="mr-2 h-4 w-4"/>Refinar</Button></div></div><div className="overflow-hidden rounded-[2rem] bg-ink text-ivory"><div className="grid lg:grid-cols-2"><div className="grid min-h-80 place-items-center" style={{background:data.palette?.[